version: '3.4'
services:
  jiuli-mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123-456
    restart: always
  
    
  jiuli-zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-3.4-latest
    links: 
      - jiuli-mysql:mysql
#    ports: 
#      - "8081:8080"
    environment:
      DB_SERVER_PORT: 3306 
      MYSQL_USER: root 
      MYSQL_PASSWORD: 123-456
    restart: always
  
  jiuli-zabbix-proxy-mysql:
      image: zabbix/zabbix-proxy-mysql:alpine-3.4-latest
      links:
        - jiuli-mysql:mysql
        - jiuli-zabbix-server-mysql:zabbix-server-mysql
      environment:
        DB_SERVER_PORT: 3306 
        MYSQL_USER: root 
        MYSQL_PASSWORD: 123-456
      restart: always
      
    
  jiuli-zabbix-agent:
      image: zabbix/zabbix-agent:alpine-3.4-latest
#      ports: 
#        - "10050:10050"
      links:
        - jiuli-zabbix-proxy-mysql:zabbix-proxy-mysql
      restart: always
   
  jiuli-zabbix-web-nginx-mysql:
      image: zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest
      links: 
        - jiuli-mysql:mysql
        - jiuli-zabbix-server-mysql:zabbix-server
      ports: 
        - "8088:80" 
      environment:
        DB_SERVER_PORT: 3306 
        MYSQL_USER: root 
        MYSQL_PASSWORD: 123-456
        TZ: "Asia/Shanghai"
      restart: always 